permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: /seu2hgx.github.io 
cdn_url: 7u2t01.com1.z0.glb.clouddn.com
lsi: false
safe: true
timezone: Asia/Shanghai
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

JB :
    #IMAGE_PATH : http://coolshell.info/images
    IMAGE_PATH : http://github.com/seu2hgx/seu2hgx.github.io/tree/master/images

# presonal config
#domain: http://coolshell.info
domain: seu2hgx.github.io
title: 浪号
description: 快乐生活,
author: Guixiang.He
email: wade_he@qq.com
github: seu2hgx

config:
  js_dir:
  img_dir:
  css_dir:
