permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: kramdown
highlights: pygments
url: http://heguixiang.github.io 
#cdn_url: 7u2t01.com1.z0.glb.clouddn.com
#lsi: false
safe: true
#timezone: Asia/Shanghai
auto: false 

paginate: 8
paginate_path: "page:num"

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

toc:
    maxDepth: 6
    slugify: false

JB :
    #IMAGE_PATH : http://coolshell.info/images
    IMAGE_PATH :  heguixiang.github.io/images

# presonal config
#domain: http://coolshell.info
domain: heguixiang.github.io
title: 浪号
description: 快乐生活
author: Guixiang.He
email: guixiang.he@outlook.com
github: heguixiang

config:
  js_dir:
  img_dir:
  css_dir:
